src/models/Post.php
<?php

/**
 * This is the model class for table "post".
 *
 * The followings are the available columns in table 'post':
 * @property string $id
 * @property string $text
 * @property string $date
 * @property int $author_id
 * @property string $user
 * @property string $dateFrom
 */
class Post extends CActiveRecord
{
	public $author_id;
	public $dateFrom;
	public $dateTo;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'post';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
			['text, date', 'required'],
			["author_id", "safe"],
			['id, text, date, user, author_id, dateFrom, dateTo', 'safe', 'on'=>'search'],
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return [
			'user' => [self::BELONGS_TO, 'User', 'author_id'],
		];
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'text' => 'Текст',
			'date' => 'Дата',
			'user' => "Автор"
		);
	}

	public function scopes(){
		return [
			'users' => [
				'with' => 'user'
			]
		];
	}

	public function defaultScope()
	{
		return [
			'alias' => 'post'
		];
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		$criteria = new CDbCriteria;
		$params = [];

		$criteria->scopes = ["users"];

		$criteria->compare('post.id', $this->id);
		$criteria->compare('post.text', $this->text, true);

		if(!empty($this->dateFrom)) {
			$criteria->addCondition("post.date >= :from");
			$params = array_merge($params, [":from" => date("Y-m-d", strtotime($this->dateFrom))]);
		}
		if(!empty($this->dateTo)) {
			$criteria->addCondition("post.date <= :to");
			$params = array_merge($params, [":to" => date("Y-m-d", strtotime($this->dateTo))]);
		}

		if(count($params))
			$criteria->params = array_merge($criteria->params, $params);

		if(!empty($this->user)){
			$criteria->addColumnCondition(['user.name' => $this->user, 'user.surname' => $this->user], "OR");
		}

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>[
				'pageSize'=>Yii::app()->params['pageSizePost'],
				'pageVar'=>'page',
			],
			'sort'=>[
				'defaultOrder'=>'post.id DESC',
			],
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * Дата в формате d.m.Y
	 * @return bool|null|string
	 */
	public function ruDate(){
		return !empty($this->date) ? date("d.m.Y", strtotime($this->date)) : null;
	}

	public function beforeSave(){
		$this->date = date("Y-m-d", strtotime($this->date));
		$this->author_id = Yii::app()->user->id;
		return parent::beforeSave();
	}

	/**
	 * Проверка на принадлежность записи текущему пользователю
	 * @return bool
	 */
	public function canShow(){
		return $this->author_id == Yii::app()->user->id;
	}

}

src/controllers/PostController.php
<?php

class PostController extends CController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column1.php'.
	 */
	public $layout='//layouts/column1';

	public $breadcrumbs=array();

	public $menu=array();

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			[
				'allow',
				'actions'=>['view','create','update', 'admin','delete'],
				'roles'=>['admin', 'user'],
			],
			['deny']
		];
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id, true);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id, true)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Post the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id, $checkUser = false)
	{
		$model = Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		if($checkUser && !$model->canShow())
			throw new CHttpException(403,'Not rules');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Post $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

src/controllers/UserController.php
<?php

class UserController extends CController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column1.php'.
	 */
	public $layout='//layouts/column1';

	public $breadcrumbs=array();

	public $menu=array();

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			[
				'allow',
				'actions'=>['view','create','update', 'admin','delete'],
				'roles'=>['admin'],
			],
			['deny']
		];
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new User("create");

		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
			'roles'=>Yii::app()->authManager->getAuthItems(CAuthItem::TYPE_ROLE)
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		$model->setScenario("update");

		$model->unsetAttributes(["password"]);
		$this->bindRoles($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];

			if($model->save())
				$this->redirect(['admin']);
		}

		$this->render('update',array(
			'model'=>$model,
			'roles'=>Yii::app()->authManager->getAuthItems(CAuthItem::TYPE_ROLE)
		));
	}

	private function bindRoles($model){
		$roles = Yii::app()->authManager->getAuthItems(CAuthItem::TYPE_ROLE, $model->id);
		if(count($roles) > 0) {
			foreach ($roles as $key => $r) {
				$model->role = [$key => $r->description];
			}
		}
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

src/views/post/_form.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'post-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'text'); ?>
		<?php echo $form->textArea($model,'text',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'text'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date'); ?>
		<?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
			'name'=>'Post[date]',
			'value' => $model->ruDate(),
			'language'=>Yii::app()->language
		)) ?>
		<?php echo $form->error($model,'date'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

src/views/post/_view.php
<?php
/* @var $this PostController */
/* @var $data Post */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('text')); ?>:</b>
	<?php echo CHtml::encode($data->text); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
	<?php echo CHtml::encode($data->date); ?>
	<br />


</div>

src/views/post/admin.php
<h1>Записи</h1>

<p><?= CHtml::link("Новая запись", Yii::app()->createUrl("post/Create")) ?> </p>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'post-grid',
	'dataProvider'=>$model->search(),
	'filter' => $model,
	'afterAjaxUpdate' => "function(){
			jQuery('#Post_dateFrom').datepicker(jQuery.extend({showMonthAfterYear:false},jQuery.datepicker.regional['ru'],[]));
			jQuery('#Post_dateTo').datepicker(jQuery.extend({showMonthAfterYear:false},jQuery.datepicker.regional['ru'],[]));
		}",
	'columns' => [
		'id',
		'text',
		[
			'name' => 'date',
			'type' => 'raw',
			'value' => 'date("d.m.Y", strtotime($data->date))',
			'filter'=>
				"От:".$this->widget('zii.widgets.jui.CJuiDatePicker', [
					'name' => 'Post[dateFrom]',
					'value' => $model->dateFrom,
					'language' => Yii::app()->language
				], true) .'<br>До:'.
				$this->widget('zii.widgets.jui.CJuiDatePicker', [
					'name' => 'Post[dateTo]',
					'value' => $model->dateTo,
					'language' => Yii::app()->language
				], true)
		],
		[
			'name'=>'user',
			'type'=>'raw',
			'value'=>'CHtml::link($data->user, Yii::app()->createUrl("/user/view", ["id" => $data->id]))'
		],
		[
			'class' => 'CButtonColumn',
			'buttons' => [
				'update' => [
					'visible' => '$data->canShow()'
				],
				'delete' => [
					'visible' => '$data->canShow()'
				]
			],
		]
	]
)); ?>

src/views/post/create.php
<h1>Создание записи</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

src/views/post/update.php
<h1>Обновить запись <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

src/views/post/view.php
<h1>Запись #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'text',
		'date',
		'user'
	),
)); ?>